### ISSUE TITLE
Do you still work on this?

### ISSUE THREAD

**Issue by JafarAkhondali** [zehratullayl/Linux-Predator-GUI#1]
Hello,
Do you still work on this project?

**Comment by zehratullayl** [comment]
Yeah. Haven't gotten time to post an update till now, but hopefully I'll be
free in another month or so i can devote time to it.

**Comment by dhruv8sh** [comment]
@zehratullayl We've been waiting...

**Comment by zehratullayl** [comment]
Yeah You can expect a stable release in 1 week 😅. I've been bug fixing and
making some UI changes.

**Comment by zehratullayl** [comment]
@JafarAkhondali @dhruv8sh 
I'm done. Am gonna push the new build tomorrow morning. I'll need some of you folks or anyone to kinda test run it and lemme know the feedback about any bugs or changes necessary 😅 .

**Comment by zehratullayl** [comment]
@JafarAkhondali @dhruv8sh it's pushed. Do check it out and let me know 😅 . I'm closing this issue for now.
